repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: "v0.9.5"
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/PyCQA/autoflake
    rev: "v2.3.1"
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variables",
          ]

  - repo: local
    hooks:
      - id: pyright
        name: Pyright Type Checking
        entry: pyright
        language: system # Assumes pyright is installed and available in your PATH
        types: [python]
